name: lib_package_demo
version : 0.0.1
description : A Demo on Library Package 
author: Test Author <testauthor@test.com>

dependencies:
  http : ^0.12.0

dev_dependencies:
  test : ^1.5.2

#environment: 
#homepage:
#documentation:
